requirements: Fix crash due to misaligned VkPhysicalDeviceFeatures
Ensure that the struct (hence the its first and only element) that holds
our byte array that represents VkPhysicalDeviceFeatures is pointer aligned.

Fixes the following crash when running vkrunner:

    thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4
    but is 0x7ffddd850925', vkrunner/libvkrunner.rlib.p/structured/requirements.rs:435:13